#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/democrud
#    username:
#    password: admin
#    driver-class-name: org.postgresql.Driver
#  main:
#    web-application-type: servlet
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
